### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by Kyzcreig** [Kurtz1993/sublime-syntax#1]
Installing “sublime-default-syntax@0.2.7” failed.Hide output…
Unable to download https://www.atom.io/api/packages/sublime-default-syntax/versions/0.2.7/tarball: 400 Bad Request Repository inaccessible

**Comment by r0oland** [comment]
Same here:
Installing “sublime-default-syntax@0.2.7” failed.Hide output…
Unable to download https://www.atom.io/api/packages/sublime-default-syntax/versions/0.2.7/tarball: 400 Bad Request Repository inaccessible

**Comment by Kurtz1993** [comment]
Could you please tell me which OS are you using?
Tested installing in Ubuntu 15.10 and worked.
Atom 1.3.2

**Comment by Kurtz1993** [comment]
Not sure what's happening but I cannot even publish a new version.

`Registering sublime-default-syntax ✗
Registering package in Kurtz1993/sublime-syntax repository failed: A package by that name already exists`

.-.

**Comment by pseisam** [comment]
Same issue here on Windows 7 x64 with atom 1.3.2

**Comment by gmist** [comment]
Same problem on OSX and Atom 1.3.3 and Atom 1.4.0-beta3

**Comment by afgallo** [comment]
Same problem Windows 10 and Atom 1.4.0

**Comment by Kurtz1993** [comment]
After a lot of attempts and errors about trying to update this package I got sick of all Atom errors so I decided to unpublish this package in the following days...
Thank you for using it.
I strongly recommend using seti-ui by jesseweed.
