### ISSUE TITLE
Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

### ISSUE THREAD

**Issue by poliverach** [Kurtz1993/sublime-syntax#1]
In index.less: Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.
If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

**Comment by Kurtz1993** [comment]
In which style or line is your suggestion exactly?
