### ISSUE TITLE
When you select a text, there is no highlighter color that shows what you are selecting? 

### ISSUE THREAD

**Issue by tizol** [Kurtz1993/sublime-syntax#10]
![sublime](https://cloud.githubusercontent.com/assets/6495684/11307183/623bb426-8f6b-11e5-9c47-36b0a0c370e3.png)

**Comment by Kurtz1993** [comment]
Which version of Atom are you using?




--------------------------------------------------------------------------------

Luis Rogelio Hernández López
luis.hlopez@outlook.com [luis.hlopez@outlook.com]
[cid:cm_1447015910087_3] [cid:cm_1447015911011_2] [http://mx.linkedin.com/in/kurtz1993] [cid:cm_1447015911683_1] [https://github.com/Kurtz1993]
Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.55&pv=5.1.1&source=email_footer_2] On Fri, Nov 20, 2015 at 11:46 am, Jose Tizol < notifications@github.com [notifications@github.com] > wrote:
sublime
[https://cloud.githubusercontent.com/assets/6495684/11307183/623bb426-8f6b-11e5-9c47-36b0a0c370e3.png]
[https://cloud.githubusercontent.com/assets/6495684/11307183/623bb426-8f6b-11e5-9c47-36b0a0c370e3.png]

**Comment by tizol** [comment]
Atom 1.2.3

**Comment by Kurtz1993** [comment]
I will take a look at that tonight.
Thank you for your feedback.

Luis Rogelio Hernández López
luis.hlopez@outlook.com [luis.hlopez@outlook.com]
[cid:cm_1447015910087_3] [cid:cm_1447015911011_2] [http://mx.linkedin.com/in/kurtz1993] [cid:cm_1447015911683_1] [https://github.com/Kurtz1993]
Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.55&pv=5.1.1&source=email_footer_2] On Fri, Nov 20, 2015 at 1:22 pm, Jose Tizol < notifications@github.com [notifications@github.com] > wrote:
Atom 1.2.3

—
Reply to this email directly or view it on GitHub
[https://github.com/Kurtz1993/sublime-syntax/issues/10#issuecomment-158500201] .[https://github.com/notifications/beacon/AFKWdsOdciX1n6pCPt-wf1YsR-vP1dTHks5pH2p0gaJpZM4Gmjj1.gif]

**Comment by tizol** [comment]
I added this to the atom style.less file:
```less
.editor .selection .region {
background-color: rgba(0, 0, 0, 0.2);
}

.editor.is-focused  .selection .region {
background-color: rgba(0, 0, 0, 0.2);
}```

and now it highlights the text that I have selected.
