### ISSUE TITLE
Default configuration not as per screenshot

### ISSUE THREAD

**Issue by lancekuttner** [Kurtz1993/sublime-syntax#2]
How do you get the theme to appear as in your screenshot? For me, the default is light coloured and I can't see how to change it.

**Comment by Kurtz1993** [comment]
Oh, I use the UI theme called Seti-UI. This package is for syntax highlight only :)

**Comment by lancekuttner** [comment]
Thanks for your response, but I am not getting much further. When I install sublime-syntax, it does not appear in the drop-down options for Syntax Theme, but it appears under UI Theme.

I then installed seti-UI, which gives me the option of Seti as a UI theme. This is getting better, but still not what I see in your screenshot.

Any chance you can provide some basic installation steps as I feel I am doing something wrong?

**Comment by Kurtz1993** [comment]
Thank you for your report! It was a mistake on the configuration file so it was appearing in UI dropdown. It should now be fixed. Reinstall the package and you'll get it now under Syntax dropdown.

**Comment by lancekuttner** [comment]
Thanks - sorted.

Most appreciated.


*Lance Kuttner*
Software Developer

Tel. 021 423 3519   Cell: 072 457 8804

[image: Saratoga - Imagine it.]
<http://www.google.com/url?q=http%3A%2F%2Fwww.saratoga.co.za%2F&sa=D&sntz=1&usg=AFrqEzfo9FDxY_b5JfKki_Fs7R4mu35iIQ>

4 Greenwich Grove, Station Rd, Rondebosch, 7700
www.saratoga.co.za
<http://www.google.com/url?q=http%3A%2F%2Fwww.saratoga.co.za%2F&sa=D&sntz=1&usg=AFrqEzfo9FDxY_b5JfKki_Fs7R4mu35iIQ>
