### ISSUE TITLE
Ubuntu 14.04 LTS (Installing “sublime-default-syntax@0.2.7” failed.Hide output…)

### ISSUE THREAD

**Issue by sadiqmmm** [Kurtz1993/sublime-syntax#3]
Installing “sublime-default-syntax@0.2.7” failed.Hide output…
![untitled](https://cloud.githubusercontent.com/assets/672989/12329638/3da97eaa-bb07-11e5-83f0-d019fd39ab26.jpg)

Unable to download https://www.atom.io/api/packages/sublime-default-syntax/versions/0.2.7/tarball: 400 Bad Request Repository inaccessible

**Comment by tradesmanhelix** [comment]
Also receiving this error when trying to install the sublime-syntax theme using the Atom package manager. Running Atom 1.4.0 on Ubuntu 14.04 LTS.

### Steps to Reproduce
preferences -> install -> themes -> search "sublime" -> install -> tries to install but fails

### View Error Message
preferences -> themes -> installed themes -> this error message is listed after attempting the above:

![atom-error](https://cloud.githubusercontent.com/assets/2421172/12332191/21690f9a-babb-11e5-8cbd-6bb91f3a4824.png)

`Unable to download https://www.atom.io/api/packages/sublime-default-syntax/versions/0.2.7/tarball: 400 Bad Request Repository inaccessible`

**Comment by Kurtz1993** [comment]
Thanks for the steps to reproduce, I will try to take a look at this. I've tried to push an update but it tells me that an existing package with that name already exists :disappointed:

**Comment by Kurtz1993** [comment]
After a lot of attempts and errors about trying to update this package I got sick of all Atom errors so I decided to unpublish this package in the following days...
Thank you for using it.
