### ISSUE TITLE
Bad cursor positioning

### ISSUE THREAD

**Issue by Namek** [Kurtz1993/sublime-syntax#9]
https://github.com/atom/atom/issues/9376

In my case cursor is translated by one whole character to the right.

It happened just today when I updated some packages, I believe there was some atom package among them. Tried to disable some of community packages that were updated but didn't change a thing.

**Comment by Kurtz1993** [comment]
I'm not having any issues with this. If possible, could you please attach a screenshot?

**Comment by Namek** [comment]
Looks same as for guys in there: https://github.com/atom/atom/issues/9343

Fix should be probably similiar to this one: https://github.com/jesseweed/seti-syntax/pull/107/files

Have you updated your Atom packages?

**Comment by Kurtz1993** [comment]
Yes, I pushed an update yesterday. I will take a look at that.
Thank you very much.

**Comment by Kurtz1993** [comment]
Already checked that particular file and I don't have that padding & margin.

**Comment by Namek** [comment]
I just noticed I had sublime-default-syntax v0.2.2. Just updated to 0.2.6 and works as previously. Not sure which version inbetween fixed that. Thanks!
